### ISSUE TITLE
Hello World

### ISSUE THREAD

**Issue by NikitaObradovic** [alptium/valentina.cupac#5]
Hello World! @nikitaobradovic

**Comment by valentinacupac** [comment]
@NikitaObradovic, I see this ticket has been opened in my repository https://github.com/alptium/valentina.cupac

Please check if that is what you intended, or did you intend instead to make it in your repository https://github.com/alptium/nikita.obradovic?

**Comment by valentinacupac** [comment]
Closing ticket, created by mistake.
